export const proteins = [
  'Bacon',
  'Beans - Black',
  'Beans - Refried',
  'Beef - Grilled',
  'Beef - Ground',
  'Beef - Shredded',
  'Carne Asada',
  'Cheese (Quesadilla)',
  'Chicken - Grilled',
  'Chicken - Mole',
  'Chicken - Shredded',
  'Chorizo (Sausage)',
  'Cochinita Pibil (Pork)',
  'Eggs',
  'Fish - Fried',
  'Fish - Grilled',
  'Lengua (Tongue)',
  'Pork',
  'Sausage',
  'Shrimp - Fried',
  'Shrimp - Grilled',
  'Tofu',
  'Tripas (Tripe)',
  'Veggie',
]

export const toppings = [
  'Avocado',
  'Cabbage',
  'Chile - Habanero',
  'Chile - Jalapeño',
  'Chile - Serrano',
  'Cilantro',
  'Crema',
  'Guacamole',
  'Lemon',
  'Lettuce',
  'Lime',
  'Onions',
  'Pineapple',
  'Red Onions',
  'Tomatoes',
]


export const salsa = [
  'Pico De Gallo',
  'Salsa - Avocado',
  'Salsa - Guajillo',
  'Salsa - Habanero',
  'Salsa - Molcajete',
  'Salsa - Red',
  'Salsa Taquera',
  'Salsa Verde',
]


export const cheese = [
  'Asadero',
  'Cheddar',
  'Chihuahua Cheese',
  'Colby Jack',
  'Cotija',
  'Feta',
  'Goat Cheese',
  'Gouda',
  'Manchego',
  'Mixed',
  'Monterrey Jack',
  'Mozzarella',
  'Panela',
  'Pepperjack',
  'Queso Anejo',
  'Queso Blanco',
  'Queso Fresco',
  'Queso Oaxaca',
  'Queso Tija',
  'Taco Blend',
  'Vegan Cheese',
]


export const tortillas = [
  'Corn - White',
  'Corn - Yellow',
  'Corn - Blue',
  'Double Tortillas',
  'Flour',
  'Grilled Cheese',
] 
