const userInfo = [ 
    {
    id: 1,
    firstName: "Gene",
    lastName: "Simmons",
    email: "kiss@me.com",
    photo: 'http://unsplash.it/75/75',
    zipCode: 97022,
    tacosPerMonth: 5,
    hardOrSoft: "soft",
    cornOrFlour: "Flour",
    heatPreference: "HOT!",
    streetOrGourmet: "street",
    favTaco: "fish",
    favTacoLocation: "Los Cucos",
    bestTacoMemory: "Best memory was in El Sorito, Mexico",
    typeOfTaco: "Beef",
    tacoLogPhoto: 'http://unsplash.it/100/100',
    restaurantName: "Los Cucos",
    rating: 3,
    notes: 'Every day is taco ipsum tuesday. Give me tacos, or give me death. Black or pinto beans? Say taco one more time. Make it a double there pal. Josh’s taco shack is the best taco shack. I think I’ve overdosed on tacos.',
    date: 'Feb 13, 2012',
    tacoName: "Big Freddy Special",
    address: "2134 West Green Lime st, San Diego, CA",
    userExperience: 'It’s raining tacos, from out of the sky, tacos, don’t even ask why. It’s long been rumored that the chupacabra is really just a crazed man who’s local taco shop went out of business. '
   },
   {
    id: 2,
    firstName: "Sammy",
    lastName: "Hagar",
    email: "redrocker@me.com",
    photo: 'http://unsplash.it/75/76',
    zipCode: 92120,
    tacosPerMonth: 3,
    hardOrSoft: "hard",
    cornOrFlour: "corn",
    heatPreference: "mild",
    streetOrGourmet: "street",
    favTaco: "fish",
    favTacoLocation: "Big Taco",
    bestTacoMemory: "Best memory was in El Sorito, Mexico",
    typeOfTaco: "Beef",
    tacoLogPhoto: 'http://unsplash.it/100/100',
    restaurantName: "Big Taco",
    rating: 3,
    notes: 'Every day is taco ipsum tuesday. Give me tacos, or give me death. Black or pinto beans? Say taco one more time. Make it a double there pal. Josh’s taco shack is the best taco shack. I think I’ve overdosed on tacos.',
    date: 'Feb 13, 2012',
    tacoName: "Fire on the Border",
    address: "2134 West Green Lime st, San Diego, CA",
    userExperience: 'It’s raining tacos, from out of the sky, tacos, don’t even ask why. It’s long been rumored that the chupacabra is really just a crazed man who’s local taco shop went out of business. '
   },
   {
    id: 3,
    firstName: "Christopher",
    lastName: "Cross",
    email: "ccross@me.com",
    photo: 'http://unsplash.it/76/75',
    zipCode: 77448,
    tacosPerMonth: 2,
    hardOrSoft: "soft",
    cornOrFlour: "Flour",
    heatPreference: "tangy",
    streetOrGourmet: "gourmet",
    favTaco: "beef",
    favTacoLocation: "Burrito Supreme",
    bestTacoMemory: "Best memory was in El Sorito, Mexico",
    typeOfTaco: "Beef",
    tacoLogPhoto: 'http://unsplash.it/100/100',
    restaurantName: "Burrito Supreme",
    rating: 3,
    notes: 'Every day is taco ipsum tuesday. Give me tacos, or give me death. Black or pinto beans? Say taco one more time. Make it a double there pal. Josh’s taco shack is the best taco shack. I think I’ve overdosed on tacos.',
    date: 'Feb 13, 2012',
    tacoName: "Tongue gold wild",
    address: "2134 West Green Lime st, San Diego, CA",
    userExperience: 'It’s raining tacos, from out of the sky, tacos, don’t even ask why. It’s long been rumored that the chupacabra is really just a crazed man who’s local taco shop went out of business. '
   }
]

export default userInfo

